export interface Warbond {
  id: string;
  nameRu: string;
  nameEn: string;
}

export interface LoadoutItem {
  id: string;
  nameRu: string;
  nameEn: string;
  category: 'primary' | 'secondary' | 'throwable' | 'booster' | 'support' | 'backpack' | 'offensive' | 'defensive' | 'armor' | 'helmet' | 'cape';
  warbond: string; // matches Warbond id
  typeRu?: string;
  typeEn?: string;
  imageUrl?: string;
}

export const WARBONDS: Warbond[] = [
  { id: 'default', nameRu: 'Мобилизация!', nameEn: 'Helldivers Mobilize!' },
  { id: 'steeled', nameRu: 'Закаленные ветераны', nameEn: 'Steeled Veterans' },
  { id: 'cutting', nameRu: 'На острие', nameEn: 'Cutting Edge' },
  { id: 'democratic', nameRu: 'Демократический детонатор', nameEn: 'Democratic Detonation' },
  { id: 'polar', nameRu: 'Полярные патриоты', nameEn: 'Polar Patriots' },
  { id: 'viper', nameRu: 'Коммандос Вайпер', nameEn: 'Viper Commandos' },
  { id: 'flame', nameRu: 'Пламя свободы', nameEn: 'Freedom\'s Flame' },
  { id: 'chemical', nameRu: 'Химические агенты', nameEn: 'Chemical Agents' },
  { id: 'truth', nameRu: 'Стражи истины', nameEn: 'Truth Enforcers' },
  { id: 'superstore', nameRu: 'Супермагазин брони', nameEn: 'Superstore' },
  { id: 'exo', nameRu: 'Экзокостюмы', nameEn: 'Exosuits' },
  { id: 'redacted', nameRu: 'Секретные разработки', nameEn: 'Redacted' },
];

export const ITEMS: LoadoutItem[] = [
  // --- BOOSTERS ---
  {
    id: 'booster-armed-resupply',
    nameRu: 'Вооруженные капсулы снабжения',
    nameEn: 'Armed Resupply Pods',
    category: 'booster',
    warbond: 'truth',
    imageUrl: './assets/boosters/Armed_Resupply_Pods_Booster_Icon.png',
  },
  {
    id: 'booster-concealed-insertion',
    nameRu: 'Скрытное проникновение',
    nameEn: 'Concealed Insertion',
    category: 'booster',
    warbond: 'redacted',
    imageUrl: './assets/boosters/Concealed_Insertion_Booster_Icon.png',
  },
  {
    id: 'booster-dead-sprint',
    nameRu: 'Смертельный спринт',
    nameEn: 'Dead Sprint',
    category: 'booster',
    warbond: 'chemical',
    imageUrl: './assets/boosters/Dead_Sprint_Booster_Icon.png',
  },
  {
    id: 'booster-experimental-infusion',
    nameRu: 'Экспериментальная инъекция',
    nameEn: 'Experimental Infusion',
    category: 'booster',
    warbond: 'viper',
    imageUrl: './assets/boosters/Experimental_Infusion_Booster_Icon.png',
  },
  {
    id: 'booster-expert-pilot',
    nameRu: 'Мастер воздушной эвакуации',
    nameEn: 'Expert Extraction Pilot',
    category: 'booster',
    warbond: 'polar',
    imageUrl: './assets/boosters/Expert_Extraction_Pilot_Booster_Icon.png',
  },
  {
    id: 'booster-firebomb-hellpods',
    nameRu: 'Огненные хэллоподы',
    nameEn: 'Firebomb Hellpods',
    category: 'booster',
    warbond: 'flame',
    imageUrl: './assets/boosters/Firebomb_Hellpods_Booster_Icon.png',
  },
  {
    id: 'booster-flexible-reinforcement',
    nameRu: 'Гибкий бюджет подкреплений',
    nameEn: 'Flexible Reinforcement Budget',
    category: 'booster',
    warbond: 'steeled',
    imageUrl: './assets/boosters/Flexible_Reinforcement_Budget_Booster_Icon.png',
  },
  {
    id: 'booster-space-optimization',
    nameRu: 'Оптимизация пространства хэллоподов',
    nameEn: 'Hellpod Space Optimization',
    category: 'booster',
    warbond: 'default',
    imageUrl: './assets/boosters/Hellpod_Space_Optimization_Booster_Icon.png',
  },
  {
    id: 'booster-increased-reinforcement',
    nameRu: 'Увеличенный бюджет подкреплений',
    nameEn: 'Increased Reinforcement Budget',
    category: 'booster',
    warbond: 'default',
    imageUrl: './assets/boosters/Increased_Reinforcement_Budget_Booster_Icon.png',
  },
  {
    id: 'booster-localization-confusion',
    nameRu: 'Позиционное заблуждение',
    nameEn: 'Localization Confusion',
    category: 'booster',
    warbond: 'democratic',
    imageUrl: './assets/boosters/Localization_Confusion_Booster_Icon.png',
  },
  {
    id: 'booster-motivational-shocks',
    nameRu: 'Мотивационные удары',
    nameEn: 'Motivational Shocks',
    category: 'booster',
    warbond: 'polar',
    imageUrl: './assets/boosters/Motivational_Shocks_Booster_Icon.png',
  },
  {
    id: 'booster-muscle-enhancement',
    nameRu: 'Повышение мускулатуры',
    nameEn: 'Muscle Enhancement',
    category: 'booster',
    warbond: 'steeled',
    imageUrl: './assets/boosters/Muscle_Enhancement_Booster_Icon.png',
  },
  {
    id: 'booster-sample-extricator',
    nameRu: 'Экстрактор образцов',
    nameEn: 'Sample Extricator',
    category: 'booster',
    warbond: 'redacted',
    imageUrl: './assets/boosters/Sample_Extricator_Booster_Icon.png',
  },
  {
    id: 'booster-sample-scanner',
    nameRu: 'Сканер образцов',
    nameEn: 'Sample Scanner',
    category: 'booster',
    warbond: 'redacted',
    imageUrl: './assets/boosters/Sample_Scanner_Booster_Icon.png',
  },
  {
    id: 'booster-stamina-enhancement',
    nameRu: 'Повышение выносливости',
    nameEn: 'Stamina Enhancement',
    category: 'booster',
    warbond: 'default',
    imageUrl: './assets/boosters/Stamina_Enhancement_Booster_Icon.png',
  },
  {
    id: 'booster-stun-pods',
    nameRu: 'Оглушающие капсулы',
    nameEn: 'Stun Pods',
    category: 'booster',
    warbond: 'redacted',
    imageUrl: './assets/boosters/Stun_Pods_Booster_Icon.png',
  },
  {
    id: 'booster-uav-recon',
    nameRu: 'Разведчик БПЛА',
    nameEn: 'UAV Recon Booster',
    category: 'booster',
    warbond: 'default',
    imageUrl: './assets/boosters/UAV_Recon_Booster_Booster_Icon.png',
  },
  {
    id: 'booster-vitality-enhancement',
    nameRu: 'Повышение жизнеспособности',
    nameEn: 'Vitality Enhancement',
    category: 'booster',
    warbond: 'default',
    imageUrl: './assets/boosters/Vitality_Enhancement_Booster_Icon.png',
  },

  // --- GEAR/ARMOR ---
  // Heavy
   {
    id: 'fs-05-marksman',
    nameRu: 'FS-05 «Меткий стрелок»',
    nameEn: 'FS-05 Marksman',
    category: 'armor',
    warbond: 'mobilize',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-FS-05_Marksman_Body_Icon.png',
  },
  {
    id: 'fs-23-battle',
    nameRu: 'FS-23 «Воевода»',
    nameEn: 'FS-23 Battle Master',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-FS-23_Battle_Master_Armor_Render.png',
  },
  {
    id: 'sa-32-dynamo',
    nameRu: 'SA-32 «Динамо»',
    nameEn: 'SA-32 Dynamo',
    category: 'armor',
    warbond: 'steeled-veterans',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-SA-32_Dynamo_Armor_Render.png',
  },
  {
    id: 'b-27-fortified-commando',
    nameRu: 'B-27 «Укрепленный коммандос»',
    nameEn: 'B-27 Fortified Commando',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-B-27_Fortified_Commando_Armor_Render.png',
  },
  {
    id: 'fs-61-dreadnought',
    nameRu: 'FS-61 «Дредноут»',
    nameEn: 'FS-61 Dreadnought',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-FS-61_Dreadnought_Armor_Render.png',
  },
  {
    id: 'fs-11-executioner',
    nameRu: 'FS-11 «Палач»',
    nameEn: 'FS-11 Executioner',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-FS-11_Executioner_Armor_Render.png',
  },
  {
    id: 'cm-17-butcher',
    nameRu: 'CM-17 «Мясник»',
    nameEn: 'CM-17 Butcher',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CM-17_Butcher_Body_Icon.png',
  },
  {
    id: 'fs-55-devastator',
    nameRu: 'FS-55 «Разрушитель»',
    nameEn: 'FS-55 Devastator',
    category: 'armor',
    warbond: 'democratic-detonation',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-FS-55_Devastator_Armor_Render.png',
  },
  {
    id: 'ce-64-grenadier',
    nameRu: 'CE-64 «Гренадер»',
    nameEn: 'CE-64 Grenadier',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CE-64_Grenadier_Body_Icon.png',
  },
  {
    id: 'cw-36-winter-warrior',
    nameRu: 'CW-36 «Зимний воин»',
    nameEn: 'CW-36 Winter Warrior',
    category: 'armor',
    warbond: 'polar-patriots',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CW-36_Winter_Warrior_Armor_Render.png',
  },
  {
    id: 'cw-22-kodiak',
    nameRu: 'CW-22 «Кадьяк»',
    nameEn: 'CW-22 Kodiak',
    category: 'armor',
    warbond: 'polar-patriots',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CW-22_Kodiak_Armor_Render.png',
  },
  {
    id: 'ce-101-guerilla-gorilla',
    nameRu: 'CE-101 «Горилла-партизан»',
    nameEn: 'CE-101 Guerilla Gorilla',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CE-101_Guerilla_Gorilla_Armor_Render.png',
  },
  {
    id: 'ph-202-twigsnapper',
    nameRu: 'PH-202 «Палколом»',
    nameEn: 'PH-202 Twigsnapper',
    category: 'armor',
    warbond: 'viper-commandos',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-PH-202_Twigsnapper_Armor_Render.png',
  },
  {
    id: 'i-44-salamander',
    nameRu: 'I-44 «Саламандра»',
    nameEn: 'I-44 Salamander',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-I-44_Salamander_Armor_Render.png',
  },
  {
    id: 'af-52-lockdown',
    nameRu: 'AF-52 «Карантин»',
    nameEn: 'AF-52 Lockdown',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-AF-52_Lockdown_Armor_Render.png',
  },
  {
    id: 'sr-64-cinderblock',
    nameRu: 'SR-64 «Шлакоблок»',
    nameEn: 'SR-64 Cinderblock',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-SR-64_Cinderblock_Armor_Render.png',
  },
  {
    id: 'sr-18-roadblock',
    nameRu: 'SR-18 «Заграждение»',
    nameEn: 'SR-18 Roadblock',
    category: 'armor',
    warbond: 'urban-legends',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-SR-18_Roadblock_Armor_Render.png',
  },
  {
    id: 'gs-66-lawmaker',
    nameRu: 'GS-66 «Законник»',
    nameEn: 'GS-66 Lawmaker',
    category: 'armor',
    warbond: 'borderline-justice',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-GS-66_Lawmaker_Armor_Render.png',
  },
  {
    id: 're-824-bearer-of-the-standard',
    nameRu: 'RE-824 «Знаменосец»',
    nameEn: 'RE-824 Bearer of the Standard',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-RE-824_Bearer_of_the_Standard_Armor_Render.png',
  },
  {
    id: 'bp-77-grand-juror',
    nameRu: 'BP-77 «Обвинительная палата»',
    nameEn: 'BP-77 Grand Juror',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-BP-77_Grand_Juror_Armor_Render.png',
  },
  {
    id: 'ad-49-apollonian',
    nameRu: 'AD-49 «Аполлон»',
    nameEn: 'AD-49 Apollonian',
    category: 'armor',
    warbond: 'control-group',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-AD-49_Apollonian_Armor_Render.png',
  },
  {
    id: 'ds-42-federations-blade',
    nameRu: 'DS-42 «Клинок Федерации»',
    nameEn: "DS-42 Federation's Blade",
    category: 'armor',
    warbond: 'dust-devils',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-DS-42_Federation%27s_Blade_Armor_Render.png',
  },
  {
    id: 'rs-40-beast-of-prey',
    nameRu: 'RS-40 «Хищник»',
    nameEn: 'RS-40 Beast of Prey',
    category: 'armor',
    warbond: 'python-commandos',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-RS-40_Beast_of_Prey_Armor_Render.png',
  },
  {
    id: 'sa-8-ram',
    nameRu: 'SA-8 «Таран»',
    nameEn: 'SA-8 Ram',
    category: 'armor',
    warbond: 'siege-breakers',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-SA-8_Ram_Armor_Render.png',
  },
  {
    id: 'cpr-80-bulwark',
    nameRu: 'CPR-80 «Бастион»',
    nameEn: 'CPR-80 Bulwark',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-CPR-80_Bulwark_Armor_Render.png',
  },
  {
    id: 'o-2-heavy-operator',
    nameRu: 'O-2 «Тяжелый оператор»',
    nameEn: 'O-2 Heavy Operator',
    category: 'armor',
    warbond: 'exo-experts',
    typeRu: 'Тяжелая броня',
    typeEn: 'Heavy Armor',
    imageUrl: './assets/gear/armor/heavy/123px-O-2_Heavy_Operator_Armor_Render.png',
  },
  // Light
  {
    id: 'sc-37-legionnaire',
    nameRu: 'SC-37 «Легионер»',
    nameEn: 'SC-37 Legionnaire',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-SC-37_Legionnaire_Armor_Render.png',
  },
  {
    id: 'sc-34-infiltrator',
    nameRu: 'SC-34 «Лазутчик»',
    nameEn: 'SC-34 Infiltrator',
    category: 'armor',
    warbond: 'mobilize',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-SC-34_Infiltrator_Armor_Render.png',
  },
  {
    id: 'sc-30-trailblazer-scout',
    nameRu: 'SC-30 «Следопыт»',
    nameEn: 'SC-30 Trailblazer Scout',
    category: 'armor',
    warbond: 'mobilize',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-SC-30_Trailblazer_Scout_Armor_Render.png',
  },
  {
    id: 'ce-74-breaker',
    nameRu: 'CE-74 «Крушитель»',
    nameEn: 'CE-74 Breaker',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CE-74_Breaker_Armor_Render.png',
  },
  {
    id: 'fs-38-eradicator',
    nameRu: 'FS-38 «Стиратель»',
    nameEn: 'FS-38 Eradicator',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-FS-38_Eradicator_Armor_Render.png',
  },
  {
    id: 'b-08-light-gunner',
    nameRu: 'B-08 «Легкий стрелок»',
    nameEn: 'B-08 Light Gunner',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-B-08_Light_Gunner_Armor_Render.png',
  },
  {
    id: 'cm-21-trench-paramedic',
    nameRu: 'CM-21 «Траншейный медик»',
    nameEn: 'CM-21 Trench Paramedic',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CM-21_Trench_Paramedic_Armor_Render.png',
  },
  {
    id: 'ce-67-titan',
    nameRu: 'CE-67 «Титан»',
    nameEn: 'CE-67 Titan',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CE-67_Titan_Armor_Render.png',
  },
  {
    id: 'ex-00-prototype-x',
    nameRu: 'EX-00 «Прототип X»',
    nameEn: 'EX-00 Prototype X',
    category: 'armor',
    warbond: 'cutting-edge',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-EX-00_Prototype_X_Armor_Render.png',
  },
  {
    id: 'ce-07-demolition-specialist',
    nameRu: 'CE-07 «Мастер-подрывник»',
    nameEn: 'CE-07 Demolition Specialist',
    category: 'armor',
    warbond: 'democratic-detonation',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CE-07_Demolition_Specialist_Armor_Render.png',
  },
  {
    id: 'fs-37-ravager',
    nameRu: 'FS-37 «Разоритель»',
    nameEn: 'FS-37 Ravager',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-FS-37_Ravager_Armor_Render.png',
  },
  {
    id: 'cw-4-arctic-ranger',
    nameRu: 'CW-4 «Арктический рейнджер»',
    nameEn: 'CW-4 Arctic Ranger',
    category: 'armor',
    warbond: 'polar-patriots',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CW-4_Arctic_Ranger_Armor_Render.png',
  },
  {
    id: 'ph-9-predator',
    nameRu: 'PH-9 «Хищник»',
    nameEn: 'PH-9 Predator',
    category: 'armor',
    warbond: 'viper-commandos',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-PH-9_Predator_Body_Icon.png',
  },
  {
    id: 'i-09-heatseeker',
    nameRu: 'I-09 «Самонаведение»',
    nameEn: 'I-09 Heatseeker',
    category: 'armor',
    warbond: 'freedoms-flame',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-I-09_Heatseeker_Armor_Render.png',
  },
  {
    id: 'af-50-noxious-ranger',
    nameRu: 'AF-50 «Ядовитый рейнджер»',
    nameEn: 'AF-50 Noxious Ranger',
    category: 'armor',
    warbond: 'chemical-agents',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-AF-50_Noxious_Ranger_Armor_Render.png',
  },
  {
    id: 'uf-16-inspector',
    nameRu: 'UF-16 «Инспектор»',
    nameEn: 'UF-16 Inspector',
    category: 'armor',
    warbond: 'truth-enforcers',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-UF-16_Inspector_Armor_Render.png',
  },
  {
    id: 'sr-24-street-scout',
    nameRu: 'SR-24 «Уличный разведчик»',
    nameEn: 'SR-24 Street Scout',
    category: 'armor',
    warbond: 'urban-legends',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-SR-24_Street_Scout_Armor_Render.png',
  },
  {
    id: 'ac-2-obedient',
    nameRu: 'AC-2 «Исполнительный»',
    nameEn: 'AC-2 Obedient',
    category: 'armor',
    warbond: 'righteous-revenants',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-AC-2_Obedient_Armor_Render.png',
  },
  {
    id: 'ie-57-hell-bent',
    nameRu: 'IE-57 «Адская решимость»',
    nameEn: 'IE-57 Hell-Bent',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-IE-57_Hell-Bent_Armor_Render.png',
  },
  {
    id: 'gs-11-democracys-deputy',
    nameRu: 'GS-11 «Посланник демократии»',
    nameEn: "GS-11 Democracy's Deputy",
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-GS-11_Democracy%27s_Deputy_Armor_Render.png',
  },
  {
    id: 're-1861-parade-commander',
    nameRu: 'RE-1861 «Командующий парадом»',
    nameEn: 'RE-1861 Parade Commander',
    category: 'armor',
    warbond: 'masters-of-ceremony',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-RE-1861_Parade_Commander_Armor_Render.png',
  },
  {
    id: 'bp-32-jackboot',
    nameRu: 'BP-32 «Ботфорт»',
    nameEn: 'BP-32 Jackboot',
    category: 'armor',
    warbond: 'force-of-law',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-BP-32_Jackboot_Armor_Render.png',
  },
  {
    id: 'ad-11-livewire',
    nameRu: 'AD-11 «Живчик»',
    nameEn: 'AD-11 Livewire',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-AD-11_Livewire_Body_Icon.png',
  },
  {
    id: 'ds-10-big-game-hunter',
    nameRu: 'DS-10 «Суперохотник»',
    nameEn: 'DS-10 Big Game Hunter',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-DS-10_Big_Game_Hunter_Armor_Render.png',
  },
  {
    id: 'rs-20-constrictor',
    nameRu: 'RS-20 «Душитель»',
    nameEn: 'RS-20 Constrictor',
    category: 'armor',
    warbond: 'python-commandos',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-RS-20_Constrictor_Armor_Render.png',
  },
  {
    id: 'rs-100-sanctioner',
    nameRu: 'RS-100 «Санкционер»',
    nameEn: 'RS-100 Sanctioner',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-RS-100_Sanctioner_Armor_Render.png',
  },
  {
    id: 'rs-89-shadow-paragon',
    nameRu: 'RS-89 «Идеальная тень»',
    nameEn: 'RS-89 Shadow Paragon',
    category: 'armor',
    warbond: 'redacted-regiment',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-RS-89_Shadow_Paragon_Armor_Render.png',
  },
  {
    id: 'cph-26-commandant',
    nameRu: 'CPH-26 «Комендант»',
    nameEn: 'CPH-26 Commandant',
    category: 'armor',
    warbond: 'entrenched-division',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-CPH-26_Commandant_Armor_Render.png',
  },
  {
    id: 'o-3-free-spirit',
    nameRu: 'O-3 «Свободный дух»',
    nameEn: 'O-3 Free Spirit',
    category: 'armor',
    warbond: 'exo-experts',
    typeRu: 'Лёгкая броня',
    typeEn: 'Light Armor',
    imageUrl: './assets/gear/armor/light/123px-O-3_Free_Spirit_Armor_Render.png',
  },
  // Medium
  {
    id: 'b-01-tactical',
    nameRu: 'B-01 «Тактик»',
    nameEn: 'B-01 Tactical',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-B-01_Tactical_v1_Armor_Render.png',
  },
  {
    id: 'ce-27-ground',
    nameRu: 'CE-27 «Первопробиватель»',
    nameEn: 'CE-27 Ground Breaker',
    category: 'armor',
    warbond: 'democratic',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CE-27_Ground_Breaker_Armor_Render.png',
  },
  {
    id: 'ce-35-trench',
    nameRu: 'CE-35 «Траншейный инженер»',
    nameEn: 'CE-35 Trench Engineer',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CE-35_Trench_Engineer_Armor_Render.png',
  },
  {
    id: 'ce-81-juggernaut',
    nameRu: 'CE-81 «Джаггернаут»',
    nameEn: 'CE-81 Juggernaut',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CE-81_Juggernaut_Armor_Render.png',
  },
  {
    id: 'cw-9-white',
    nameRu: 'CW-9 «Белый волк»',
    nameEn: 'CW-9 White Wolf',
    category: 'armor',
    warbond: 'polar',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CW-9_White_Wolf_Armor_Render.png',
  },
  {
    id: 'ex-03-prototype',
    nameRu: 'EX-03 «Прототип 3»',
    nameEn: 'EX-03 Prototype 3',
    category: 'armor',
    warbond: 'cutting',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-EX-03_Prototype_3_Armor_Render.png',
  },
  {
    id: 'sa-25-steel',
    nameRu: 'SA-25 «Стальной кавалерист»',
    nameEn: 'SA-25 Steel Trooper',
    category: 'armor',
    warbond: 'steeled',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-SA-25_Steel_Trooper_Armor_Render.png',
  },
  {
    id: 'sa-12-servo',
    nameRu: 'SA-12 «Сервоприводная»',
    nameEn: 'SA-12 Servo Assisted',
    category: 'armor',
    warbond: 'steeled',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-SA-12_Servo_Assisted_Armor_Render.png',
  },
  {
    id: 'sc-15-drone',
    nameRu: 'SC-15 «Командир дронов»',
    nameEn: 'SC-15 Drone Master',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-SC-15_Drone_Master_Armor_Render.png',
  },
  {
    id: 'cm-09-bonesnapper',
    nameRu: 'CM-09 «Костолом»',
    nameEn: 'CM-09 Bonesnapper',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CM-09_Bonesnapper_Armor_Render.png',
  },
  {
    id: 'cm-10-clinician',
    nameRu: 'CM-10 «Клиницист»',
    nameEn: 'CM-10 Clinician',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CM-10_Clinician_Armor_Render.png',
  },
  {
    id: 'cm-14-physician',
    nameRu: 'CM-14 «Врач»',
    nameEn: 'CM-14 Physician',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-CM-14_Physician_Armor_Render.png',
  },
  {
    id: 'tr-117-alpha-commander',
    nameRu: 'TR-117 «Альфа-командир»',
    nameEn: 'TR-117 Alpha Commander',
    category: 'armor',
    warbond: 'twitch-drop',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-TR-117_Alpha_Commander_Armor_Render.png',
  },
  {
    id: 'dp-40-hero',
    nameRu: 'DP-40 «Герой Федерации»',
    nameEn: 'DP-40 Hero of the Federation',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-DP-40_Hero_of_the_Federation_Armor_Render.png',
  },
  {
    id: 'dp-11-champion',
    nameRu: 'DP-11 «Защитник народа»',
    nameEn: 'DP-11 Champion of the People',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-DP-11_Champion_of_the_People_Armor_Render.png',
  },
  {
    id: 'dp-53-savior',
    nameRu: 'DP-53 «Спаситель свободы»',
    nameEn: 'DP-53 Saviour of the Free',
    category: 'armor',
    warbond: 'super-citizen',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-DP-53_Saviour_of_the_Free_Armor_Render.png',
  },
  {
    id: 'fs-34-exterminator',
    nameRu: 'FS-34 «Уничтожитель»',
    nameEn: 'FS-34 Exterminator',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-FS-34_Exterminator_Armor_Render.png',
  },
  {
    id: 'b-24-enforcer',
    nameRu: 'B-24 «Вышибала»',
    nameEn: 'B-24 Enforcer',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-B-24_Enforcer_Armor_Render.png',
  },
  {
    id: 'sa-04-combat',
    nameRu: 'SA-04 «Боевой техник»',
    nameEn: 'SA-04 Combat Technician',
    category: 'armor',
    warbond: 'default',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-SA-04_Combat_Technician_Armor_Render.png',
  },
  {
    id: 'a-9-helljumper',
    nameRu: 'A-9 «Адский прыгун»',
    nameEn: 'A-9 Helljumper',
    category: 'armor',
    warbond: 'halo',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-A-9_Helljumper_Armor_Render.png',
  },
  {
    id: 'a-35-recon',
    nameRu: 'A-35 «Разведчик»',
    nameEn: 'A-35 Recon',
    category: 'armor',
    warbond: 'halo',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-A-35_Recon_Armor_Render.png',
  },
  {
    id: 'ie-3-martyr',
    nameRu: 'IE-3 «Мученик»',
    nameEn: 'IE-3 Martyr',
    category: 'armor',
    warbond: 'freedom-servants',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-IE-3_Martyr_Armor_Render.png',
  },
  {
    id: 'ie-12-righteous',
    nameRu: 'IE-12 «Праведник»',
    nameEn: 'IE-12 Righteous',
    category: 'armor',
    warbond: 'freedom-servants',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-IE-12_Righteous_Armor_Render.png',
  },
  {
    id: 'gs-17-frontier',
    nameRu: 'GS-17 «Шериф Пограничья»',
    nameEn: 'GS-17 Frontier Marshal',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-GS-17_Frontier_Marshal_Armor_Render.png',
  },
  {
    id: 're-2310-honorary',
    nameRu: 'RE-2310 «Почетный караул»',
    nameEn: 'RE-2310 Honorary Guard',
    category: 'armor',
    warbond: 'masters',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-RE-2310_Honorary_Guard_Armor_Render.png',
  },
  {
    id: 'ad-26-bleeding',
    nameRu: 'AD-26 «Кровавая грань»',
    nameEn: 'AD-26 Bleeding Edge',
    category: 'armor',
    warbond: 'cutting',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-AD-26_Bleeding_Edge_Armor_Render.png',
  },
  {
    id: 'uf-84-doubt',
    nameRu: 'UF-84 «Убийца сомнений»',
    nameEn: 'UF-84 Doubt Killer',
    category: 'armor',
    warbond: 'truth',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-UF-84_Doubt_Killer_Armor_Render.png',
  },
  {
    id: 'uf-50-bloodhound',
    nameRu: 'UF-50 «Кровавая гончая»',
    nameEn: 'UF-50 Bloodhound',
    category: 'armor',
    warbond: 'truth',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-UF-50_Bloodhound_Armor_Render.png',
  },
  {
    id: 'ph-56-jaguar',
    nameRu: 'PH-56 «Ягуар»',
    nameEn: 'PH-56 Jaguar',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-PH-56_Jaguar_Armor_Render.png',
  },
  {
    id: 'bp-20-corrections',
    nameRu: 'BP-20 «Офицер по корректировке»',
    nameEn: 'BP-20 Corrections Officer',
    category: 'armor',
    warbond: 'force-of-law',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-BP-20_Corrections_Officer_Armor_Render.png',
  },
  {
    id: 'ex-16-prototype',
    nameRu: 'EX-16 «Прототип 16»',
    nameEn: 'EX-16 Prototype 16',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-EX-16_Prototype_16_Armor_Render.png',
  },
  {
    id: 'af-91-field',
    nameRu: 'AF-91 «Полевой химик»',
    nameEn: 'AF-91 Field Chemist',
    category: 'armor',
    warbond: 'chemical',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-AF-91_Field_Chemist_Armor_Render.png',
  },
  {
    id: 'af-02-hazmaster',
    nameRu: 'AF-02 «Хим-мастер»',
    nameEn: 'AF-02 Haz-Master',
    category: 'armor',
    warbond: 'superstore',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-AF-02_Haz-Master_Armor_Render.png',
  },
  {
    id: 'i-92-firefighter',
    nameRu: 'I-92 «Пожарный»',
    nameEn: 'I-92 Fire Fighter',
    category: 'armor',
    warbond: 'fire',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-I-92_Fire_Fighter_Armor_Render.png',
  },
  {
    id: 'i-102-draconaught',
    nameRu: 'I-102 «Драгонавт»',
    nameEn: 'I-102 Draconaught',
    category: 'armor',
    warbond: 'fire',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-I-102_Draconaught_Armor_Render.png',
  },
  {
    id: 'ac-1-dutiful',
    nameRu: 'AC-1 «Добросовестный»',
    nameEn: 'AC-1 Dutiful',
    category: 'armor',
    warbond: 'righteous',
    typeRu: 'Средняя броня',
    typeEn: 'Medium Armor',
    imageUrl: './assets/gear/armor/medium/123px-AC-1_Dutiful_Armor_Render.png',
  },

  // --- STRATAGEMS/DEFENSIVE_PERMIT ---
  // Emplacements
  {
    id: 'anti-personnel-mines',
    nameRu: 'MD-6 «Противопехотное минное поле»',
    nameEn: 'MD-6 Anti-Personnel Minefield',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Anti-Personnel_Minefield_Stratagem_Icon_Background.png',
  },
  {
    id: 'anti-tank-emplacement',
    nameRu: 'E/AT-12 «Противотанковая турель»',
    nameEn: 'E/AT-12 Anti-Tank Emplacement',
    category: 'defensive',
    warbond: 'redacted',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Bridge Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Anti-Tank_Emplacement_Stratagem_Icon_Background.png',
  },
  {
    id: 'anti-tank-mines',
    nameRu: 'MD-17 «Противотанковые мины»',
    nameEn: 'MD-17 Anti-Tank Mines',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Anti-Tank_Mines_Stratagem_Icon_Background.png',
  },
  {
    id: 'gas-mines',
    nameRu: 'MD-8 «Газовые мины»',
    nameEn: 'MD-8 Gas Mines',
    category: 'defensive',
    warbond: 'chemical',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Gas_Mines_Stratagem_Icon_Background.png',
  },
  {
    id: 'grenadier-battlement',
    nameRu: 'E/GL-21 «Гранатометная позиция»',
    nameEn: 'E/GL-21 Grenadier Battlement',
    category: 'defensive',
    warbond: 'redacted',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Bridge Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Grenadier_Battlement_Stratagem_Icon_Background.png',
  },
  {
    id: 'hmg-emplacement',
    nameRu: 'E/MG-101 «Тяжелая пулеметная установка»',
    nameEn: 'E/MG-101 HMG Emplacement',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Bridge Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/HMG_Emplacement_Stratagem_Icon_Background.png',
  },
  {
    id: 'incendiary-mines',
    nameRu: 'MD-I4 «Зажигательные мины»',
    nameEn: 'MD-I4 Incendiary Mines',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Incendiary_Mines_Stratagem_Icon_Background.png',
  },
  {
    id: 'shield-relay',
    nameRu: 'FX-12 «Реле генератора щита»',
    nameEn: 'FX-12 Shield Generator Relay',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/emplacements/Shield_Generator_Relay_Stratagem_Icon_Background.png',
  },
  // Sentries
  {
    id: 'autocannon-sentry',
    nameRu: 'A/AC-8 «Турель-автопушка»',
    nameEn: 'A/AC-8 Autocannon Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Autocannon_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'mortar-sentry',
    nameRu: 'A/M-12 «Минометная турель»',
    nameEn: 'A/M-12 Mortar Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/EMS_Mortar_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'ems-mortar-sentry',
    nameRu: 'A/M-23 «ЭМ-минометная турель»',
    nameEn: 'A/M-23 EMS Mortar Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/EMS_Mortar_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'flame-sentry',
    nameRu: 'A/FLAM-40 «Огнеметная турель»',
    nameEn: 'A/FLAM-40 Flame Sentry',
    category: 'defensive',
    warbond: 'flame',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Flame_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'gas-mortar-sentry',
    nameRu: 'A/GM-17 «Газовая минометная турель»',
    nameEn: 'A/GM-17 Gas Mortar Sentry',
    category: 'defensive',
    warbond: 'chemical',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Gas_Mortar_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'gatling-sentry',
    nameRu: 'A/G-16 «Турель Гатлинга»',
    nameEn: 'A/G-16 Gatling Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Gatling_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'laser-sentry',
    nameRu: 'A/LAS-98 «Лазерная турель»',
    nameEn: 'A/LAS-98 Laser Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Laser_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'machine-gun-sentry',
    nameRu: 'A/MG-43 «Турель-пулемет»',
    nameEn: 'A/MG-43 Machine Gun Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Machine_Gun_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'rocket-sentry',
    nameRu: 'A/MLS-4X «Ракетная турель»',
    nameEn: 'A/MLS-4X Rocket Sentry',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Robotics Workshop Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Rocket_Sentry_Stratagem_Icon_Background.png',
  },
  {
    id: 'tesla-tower',
    nameRu: 'A/ARC-3 «Башня Тесла»',
    nameEn: 'A/ARC-3 Tesla Tower',
    category: 'defensive',
    warbond: 'default',
    typeRu: 'Оборонительная стратагема',
    typeEn: 'Engineering Bay Stratagem',
    imageUrl: './assets/stratagems/defensive_permit/sentries/Tesla_Tower_Stratagem_Icon_Background.png',
  },

  // --- STRATAGEMS/OFFENSIVE_PERMIT ---
  // Eagle Strikes
  {
    id: 'eagle-110mm',
    nameRu: 'Орёл: 110-мм ракетные кассеты',
    nameEn: 'Eagle 110mm Rocket Pods',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_110mm_Rocket_Pods_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-500kg',
    nameRu: 'Орёл: 500-кг бомба',
    nameEn: 'Eagle 500kg Bomb',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_500kg_Bomb_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-airstrike',
    nameRu: 'Орёл: Воздушный налет',
    nameEn: 'Eagle Airstrike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_Airstrike_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-cluster',
    nameRu: 'Орёл: Кассетная бомба',
    nameEn: 'Eagle Cluster Bomb',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_Cluster_Bomb_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-napalm',
    nameRu: 'Орёл: Напалмовый авиаудар',
    nameEn: 'Eagle Napalm Airstrike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_Napalm_Airstrike_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-smoke',
    nameRu: 'Орёл: Дымовой удар',
    nameEn: 'Eagle Smoke Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_Smoke_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'eagle-strafing',
    nameRu: 'Орёл: Бреющий полет',
    nameEn: 'Eagle Strafing Run',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Авиаудар «Орла»',
    typeEn: 'Hangar Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/eagle_strikes/Eagle_Strafing_Run_Stratagem_Icon_Background.png',
  },
  // Orbital Strikes
  {
    id: 'orbital-120-he',
    nameRu: 'Орбитальный 120-мм фугасный обстрел',
    nameEn: 'Orbital 120mm HE Barrage',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_120mm_HE_Barrage_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-380-he',
    nameRu: 'Орбитальный 380-мм фугасный обстрел',
    nameEn: 'Orbital 380mm HE Barrage',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_380mm_HE_Barrage_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-airburst',
    nameRu: 'Орбитальная воздушная бомба',
    nameEn: 'Orbital Airburst Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Airburst_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-ems',
    nameRu: 'Орбитальный ЭМ-удар',
    nameEn: 'Orbital EMS Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_EMS_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-gas',
    nameRu: 'Орбитальный газовый удар',
    nameEn: 'Orbital Gas Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Gas_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-gatling',
    nameRu: 'Орбитальный обстрел из Гатлинга',
    nameEn: 'Orbital Gatling Barrage',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Gatling_Barrage_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-laser',
    nameRu: 'Орбитальный лазер',
    nameEn: 'Orbital Laser',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Laser_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-napalm',
    nameRu: 'Орбитальный обстрел напалмом',
    nameEn: 'Orbital Napalm Barrage',
    category: 'offensive',
    warbond: 'flame',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Napalm_Barrage_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-precision',
    nameRu: 'Орбитальный точечный удар',
    nameEn: 'Orbital Precision Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Precision_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-railcannon',
    nameRu: 'Орбитальный удар рельсотроном',
    nameEn: 'Orbital Railcannon Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Railcannon_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-smoke',
    nameRu: 'Орбитальный дымовой удар',
    nameEn: 'Orbital Smoke Strike',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Smoke_Strike_Stratagem_Icon_Background.png',
  },
  {
    id: 'orbital-walking',
    nameRu: 'Орбитальный заградительный обстрел',
    nameEn: 'Orbital Walking Barrage',
    category: 'offensive',
    warbond: 'default',
    typeRu: 'Орбитальный удар',
    typeEn: 'Orbital Cannon Stratagem',
    imageUrl: './assets/stratagems/offensive_permit/orbital_strikes/Orbital_Walking_Barrage_Stratagem_Icon_Background.png',
  },

  // --- STRATAGEMS/SUPPLY_PERMIT ---
  // Backpacks
  {
    id: 'ballistic-shield',
    nameRu: 'SH-20 «Баллистический щит»',
    nameEn: 'SH-20 Ballistic Shield Backpack',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Ballistic_Shield_Backpack_Stratagem_Icon_Background.png',
  },
  {
    id: 'directional-shield',
    nameRu: 'SH-51 «Направленный щит»',
    nameEn: 'SH-51 Directional Shield',
    category: 'backpack',
    warbond: 'truth',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Directional_Shield_Stratagem_Icon_Background.png',
  },
  {
    id: 'dog-breath',
    nameRu: 'AX/TX-13 «Дыхание пса»',
    nameEn: 'AX/TX-13 Dog Breath',
    category: 'backpack',
    warbond: 'chemical',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Dog_Breath_Stratagem_Icon_Background.png',
  },
  {
    id: 'guard-dog-bullet',
    nameRu: 'AX/AR-23 «Сторожевой пес»',
    nameEn: 'AX/AR-23 Guard Dog',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Guard_Dog_Stratagem_Icon_Background.png',
  },
  {
    id: 'hot-dog',
    nameRu: 'AX/FLAM-75 «Хот-дог»',
    nameEn: 'AX/FLAM-75 Hot Dog',
    category: 'backpack',
    warbond: 'flame',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Hot_Dog_Stratagem_Icon_Background.png',
  },
  {
    id: 'hover-pack',
    nameRu: 'LIFT-860 «Реактивный ранец»',
    nameEn: 'LIFT-860 Hover Pack',
    category: 'backpack',
    warbond: 'redacted',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Hover_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'jump-pack',
    nameRu: 'LIFT-850 «Прыжковый ранец»',
    nameEn: 'LIFT-850 Jump Pack',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Jump_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'portable-hellbomb',
    nameRu: 'B-100 «Портативная хэллбомба»',
    nameEn: 'B-100 Portable Hellbomb',
    category: 'backpack',
    warbond: 'redacted',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Portable_Hellbomb_Stratagem_Icon_Background.png',
  },
  {
    id: 'guard-dog-laser',
    nameRu: 'AX/LAS-5 «Аппарат»',
    nameEn: 'AX/LAS-5 Rover',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Rover_Stratagem_Icon_Background.png',
  },
  {
    id: 'shield-generator-pack',
    nameRu: 'SH-32 «Рюкзак-генератор щита»',
    nameEn: 'SH-32 Shield Generator Pack',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Shield_Generator_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'supply-pack',
    nameRu: 'B-1 «Рюкзак с припасами»',
    nameEn: 'B-1 Supply Pack',
    category: 'backpack',
    warbond: 'default',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Supply_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'warp-pack',
    nameRu: 'LIFT-182 «Варп-ранец»',
    nameEn: 'LIFT-182 Warp Pack',
    category: 'backpack',
    warbond: 'redacted',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/Warp_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'k-9-backpack',
    nameRu: 'AX/ARC-3 «К-9»',
    nameEn: 'AX/ARC-3 K-9',
    category: 'backpack',
    warbond: 'redacted',
    typeRu: 'Рюкзак',
    typeEn: 'Backpack Stratagem',
    imageUrl: './assets/stratagems/supply_permit/backpacks/K-9_Stratagem_Icon_Background.png',
  },
  // Support Weapons
  {
    id: 'airburst-rocket',
    nameRu: 'RL-77 «Ракетница с подрывом в воздухе»',
    nameEn: 'RL-77 Airburst Rocket Launcher',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Airburst_Rocket_Launcher_Stratagem_Icon_Background.png',
  },
  {
    id: 'anti-materiel-rifle',
    nameRu: 'APW-1 «Крупнокалиберная винтовка»',
    nameEn: 'APW-1 Anti-Materiel Rifle',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Anti-Materiel_Rifle_Stratagem_Icon_Background.png',
  },
  {
    id: 'arc-thrower',
    nameRu: 'ARC-3 «Дуговой метатель»',
    nameEn: 'ARC-3 Arc Thrower',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Arc_Thrower_Stratagem_Icon_Background.png',
  },
  {
    id: 'autocannon',
    nameRu: 'AC-8 «Автопушка»',
    nameEn: 'AC-8 Autocannon',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Autocannon_Stratagem_Icon_Background.png',
  },
  {
    id: 'grenade-launcher',
    nameRu: 'GL-21 «Гранатомёт»',
    nameEn: 'GL-21 Grenade Launcher',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Belt-Fed_Grenade_Launcher_Stratagem_Icon_Background.png',
  },
  {
    id: 'gl-28-belt-fed',
    nameRu: 'GL-28 «Ленточный гранатомет»',
    nameEn: 'GL-28 Belt-Fed Grenade Launcher',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Belt-Fed_Grenade_Launcher_Stratagem_Icon_Background.png',
  },
  {
    id: 'breaching-hammer',
    nameRu: 'CQC-20 «Штурмовой молот»',
    nameEn: 'CQC-20 Breaching Hammer',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Breaching_Hammer_Stratagem_Icon_Background.png',
  },
  {
    id: 'bullet-storm',
    nameRu: 'MGX-42 «Шквал пуль»',
    nameEn: 'MGX-42 Bullet Storm',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Bullet_Storm_Stratagem_Icon_Background.png',
  },
  {
    id: 'c4-pack',
    nameRu: 'B/MD «Взрывчатка C4»',
    nameEn: 'B/MD C4 Pack',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/C4_Pack_Stratagem_Icon_Background.png',
  },
  {
    id: 'commando',
    nameRu: 'MLS-4X «Коммандо»',
    nameEn: 'MLS-4X Commando',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Commando_Stratagem_Icon_Background.png',
  },
  {
    id: 'cremator',
    nameRu: 'B/FLAM-80 «Крематор»',
    nameEn: 'B/FLAM-80 Cremator',
    category: 'support',
    warbond: 'flame',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Cremator_Stratagem_Icon_Background.png',
  },
  {
    id: 'gl-52-deescalator',
    nameRu: 'GL-52 «Деэскалатор»',
    nameEn: 'GL-52 De-Escalator',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/De-Escalator_Stratagem_Icon_Background.png',
  },
  {
    id: 'defoliation-tool',
    nameRu: 'CQC-9 «Дефолиатор»',
    nameEn: 'CQC-9 Defoliation Tool',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Defoliation_Tool_Stratagem_Icon_Background.png',
  },
  {
    id: 'plas-45-epoch',
    nameRu: 'PLAS-45 «Эпоха»',
    nameEn: 'PLAS-45 Epoch',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Epoch_Stratagem_Icon_Background.png',
  },
  {
    id: 'expendable-anti-tank',
    nameRu: 'EAT-17 «Одноразовый бронебой»',
    nameEn: 'EAT-17 Expendable Anti-Tank',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Expendable_Anti-Tank_Stratagem_Icon_Background.png',
  },
  {
    id: 'flamethrower',
    nameRu: 'FLAM-40 «Огнемёт»',
    nameEn: 'FLAM-40 Flamethrower',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Flamethrower_Stratagem_Icon_Background.png',
  },
  {
    id: 'machine-gun',
    nameRu: 'MG-43 «Пулемёт»',
    nameEn: 'MG-43 Machine Gun',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Heavy_Machine_Gun_Stratagem_Icon_Background.png',
  },
  {
    id: 'heavy-machine-gun',
    nameRu: 'MG-206 «Тяжёлый пулемёт»',
    nameEn: 'MG-206 Heavy Machine Gun',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Heavy_Machine_Gun_Stratagem_Icon_Background.png',
  },
  {
    id: 'laser-cannon',
    nameRu: 'LAS-98 «Лазерная пушка»',
    nameEn: 'LAS-98 Laser Cannon',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Laser_Cannon_Stratagem_Icon_Background.png',
  },
  {
    id: 'eat-411-leveller',
    nameRu: 'EAT-411 «Уравнитель»',
    nameEn: 'EAT-411 Leveller',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Leveller_Stratagem_Icon_Background.png',
  },
  {
    id: 'maxigun',
    nameRu: 'M-1000 «Максиган»',
    nameEn: 'M-1000 Maxigun',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Maxigun_Stratagem_Icon_Background.png',
  },
  {
    id: 'one-true-flag',
    nameRu: 'CQC-1 «Единственный флаг»',
    nameEn: 'CQC-1 One True Flag',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/One_True_Flag_Stratagem_Icon_Background.png',
  },
  {
    id: 'quasar-cannon',
    nameRu: 'LAS-99 Пушка «Квазар»',
    nameEn: 'LAS-99 Quasar Cannon',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Quasar_Cannon_Stratagem_Icon_Background.png',
  },
  {
    id: 'railgun',
    nameRu: 'RS-422 «Рельсотрон»',
    nameEn: 'RS-422 Railgun',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Railgun_Stratagem_Icon_Background.png',
  },
  {
    id: 'recoilless-rifle',
    nameRu: 'GR-8 «Безоткатная винтовка»',
    nameEn: 'GR-8 Recoilless Rifle',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Recoilless_Rifle_Stratagem_Icon_Background.png',
  },
  {
    id: 'solo-silo',
    nameRu: 'MS-11 «Одиночная шахта»',
    nameEn: 'MS-11 Solo Silo',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Solo_Silo_Stratagem_Icon_Background.png',
  },
  {
    id: 'spear',
    nameRu: 'FAF-14 «Копьё»',
    nameEn: 'FAF-14 Spear',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Speargun_Stratagem_Icon_Background.png',
  },
  {
    id: 'speargun',
    nameRu: 'S-11 «Гарпун»',
    nameEn: 'S-11 Speargun',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Speargun_Stratagem_Icon_Background.png',
  },
  {
    id: 'stalwart',
    nameRu: 'M-105 «Доблесть»',
    nameEn: 'M-105 Stalwart',
    category: 'support',
    warbond: 'default',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Stalwart_Stratagem_Icon_Background.png',
  },
  {
    id: 'wasp-launcher',
    nameRu: 'StA-X3 «Пусковая установка ОСА»',
    nameEn: 'StA-X3 W.A.S.P. Launcher',
    category: 'support',
    warbond: 'redacted',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/W.A.S.P._Launcher_Stratagem_Icon_Background.png',
  },
  {
    id: 'sterilizer',
    nameRu: 'TX-41 «Стерилизатор»',
    nameEn: 'TX-41 Sterilizer',
    category: 'support',
    warbond: 'chemical',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Sterilizer_Stratagem_Icon_Background.png',
  },
  {
    id: 'expendable-napalm',
    nameRu: 'EAT-700 «Одноразовый напалм»',
    nameEn: 'EAT-700 Expendable Napalm',
    category: 'support',
    warbond: 'flame',
    typeRu: 'Вспомогательное оружие',
    typeEn: 'Support Weapon Stratagem',
    imageUrl: './assets/stratagems/supply_permit/support_weapons/Expendable_Napalm_Stratagem_Icon_Background.png',
  },
  // Vehicles
  {
    id: 'supply-frv',
    nameRu: 'M-103 «Машина снабжения»',
    nameEn: 'M-103 Supply FRV',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Транспорт',
    typeEn: 'Vehicle Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Supply_FRV_Stratagem_Icon_Background.png',
  },
  {
    id: 'incinerator-frv',
    nameRu: 'M-104 «Огнеметная машина»',
    nameEn: 'M-104 Incinerator FRV',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Транспорт',
    typeEn: 'Vehicle Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Incinerator_FRV_Stratagem_Icon_Background.png',
  },
  {
    id: 'emancipator-exosuit',
    nameRu: 'EXO-49 Экзокостюм «Освободитель»',
    nameEn: 'EXO-49 Emancipator Exosuit',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Экзокостюм',
    typeEn: 'Exosuit Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Emancipator_Exosuit_Stratagem_Icon_Background.png',
  },
  {
    id: 'patriot-exosuit',
    nameRu: 'EXO-45 Экзокостюм «Патриот»',
    nameEn: 'EXO-45 Patriot Exosuit',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Экзокостюм',
    typeEn: 'Exosuit Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Patriot_Exosuit_Stratagem_Icon_Background.png',
  },
  {
    id: 'recon-vehicle',
    nameRu: 'M-102 «Легкая разведывательная машина»',
    nameEn: 'M-102 Fast Recon Vehicle',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Транспорт',
    typeEn: 'Vehicle Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Fast_Recon_Vehicle_Stratagem_Icon_Background.png',
  },
  {
    id: 'bastion-tank',
    nameRu: 'TD-220 «Бастион MK XVI»',
    nameEn: 'TD-220 Bastion MK XVI',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Транспорт',
    typeEn: 'Vehicle Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Bastion_MK_XVI_Stratagem_Icon_Background.png',
  },
  {
    id: 'breakthrough-exosuit',
    nameRu: 'EXO-55 Экзокостюм «Прорыв»',
    nameEn: 'EXO-55 Breakthrough Exosuit',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Экзокостюм',
    typeEn: 'Exosuit Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Breakthrough_Exosuit_Stratagem_Icon_Background.png',
  },
  {
    id: 'lumberer-exosuit',
    nameRu: 'EXO-51 Экзокостюм «Лесоруб»',
    nameEn: 'EXO-51 Lumberer Exosuit',
    category: 'support',
    warbond: 'exo',
    typeRu: 'Экзокостюм',
    typeEn: 'Exosuit Stratagem',
    imageUrl: './assets/stratagems/supply_permit/vehicles/Lumberer_Exosuit_Stratagem_Icon_Background.png',
  },

  // --- THROWABLES/SPECIAL ---
  {
    id: 'g-109-urchin',
    nameRu: 'G-109 «Озорник»',
    nameEn: 'G-109 Urchin',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Игольчатая граната',
    typeEn: 'Urchin Grenade',
    imageUrl: './assets/throwables/special/G-109_Urchin_Throwable_Render.png',
  },
  {
    id: 'thermite-grenade',
    nameRu: 'G-123 «Термитная»',
    nameEn: 'G-123 Thermite',
    category: 'throwable',
    warbond: 'democratic',
    typeRu: 'Термитная граната',
    typeEn: 'Thermite Grenade',
    imageUrl: './assets/throwables/special/G-123_Thermite_Throwable_Render.png',
  },
  {
    id: 'g-13-incendiary-impact',
    nameRu: 'G-13 «Зажигательная ударная»',
    nameEn: 'G-13 Incendiary Impact',
    category: 'throwable',
    warbond: 'flame',
    typeRu: 'Зажигательная граната',
    typeEn: 'Incendiary Impact Grenade',
    imageUrl: './assets/throwables/special/G-13_Incendiary_Impact_Throwable_Render.png',
  },
  {
    id: 'g-142-pyrotech',
    nameRu: 'G-142 «Пиротех»',
    nameEn: 'G-142 Pyrotech',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Сигнальная граната',
    typeEn: 'Pyrotech Grenade',
    imageUrl: './assets/throwables/special/G-142_Pyrotech_Throwable_Render.png',
  },
  {
    id: 'impact-grenade',
    nameRu: 'G-16 «Ударная»',
    nameEn: 'G-16 Impact',
    category: 'throwable',
    warbond: 'default',
    typeRu: 'Контактная граната',
    typeEn: 'Impact Grenade',
    imageUrl: './assets/throwables/special/G-16_Impact_Throwable_Render.png',
  },
  {
    id: 'stun-grenade',
    nameRu: 'G-23 «Оглушающая»',
    nameEn: 'G-23 Stun',
    category: 'throwable',
    warbond: 'cutting',
    typeRu: 'Светошумовая граната',
    typeEn: 'Stun Grenade',
    imageUrl: './assets/throwables/special/G-23_Stun_Throwable_Render.png',
  },
  {
    id: 'g-31-arc',
    nameRu: 'G-31 «Дуговая»',
    nameEn: 'G-31 Arc',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Дуговая граната',
    typeEn: 'Arc Grenade',
    imageUrl: './assets/throwables/special/G-31_ARC_Throwable_Render.png',
  },
  {
    id: 'smoke-grenade',
    nameRu: 'G-3 «Дымовая»',
    nameEn: 'G-3 Smoke',
    category: 'throwable',
    warbond: 'default',
    typeRu: 'Дымовая граната',
    typeEn: 'Smoke Grenade',
    imageUrl: './assets/throwables/special/G-3_Smoke_Throwable_Render.png',
  },
  {
    id: 'g-48-giga',
    nameRu: 'G-48 «Гига-граната»',
    nameEn: 'G-48 Giga Grenade',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Тяжелая граната',
    typeEn: 'Heavy Grenade',
    imageUrl: './assets/throwables/special/G-48_Giga_Grenade_Throwable_Render.png',
  },
  {
    id: 'g-4-gas',
    nameRu: 'G-4 «Газовая»',
    nameEn: 'G-4 Gas',
    category: 'throwable',
    warbond: 'chemical',
    typeRu: 'Газовая граната',
    typeEn: 'Gas Grenade',
    imageUrl: './assets/throwables/special/G-4_Gas_Throwable_Render.png',
  },
  {
    id: 'g-50-seeker',
    nameRu: 'G-50 «Искатель»',
    nameEn: 'G-50 Seeker',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Умная граната',
    typeEn: 'Seeker Grenade',
    imageUrl: './assets/throwables/special/G-50_Seeker_Throwable_Render.png',
  },
  {
    id: 'g-89-smokescreen',
    nameRu: 'G-89 «Дымовая завеса»',
    nameEn: 'G-89 Smokescreen',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Дымовая завеса',
    typeEn: 'Smokescreen Grenade',
    imageUrl: './assets/throwables/special/G-89_Smokescreen_Throwable_Render.png',
  },
  {
    id: 'g-sh-39-shield',
    nameRu: 'G/SH-39 «Щит»',
    nameEn: 'G/SH-39 Shield',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Генераторный щит',
    typeEn: 'Shield Grenade',
    imageUrl: './assets/throwables/special/G-SH-39_Shield_Throwable_Render.png',
  },
  {
    id: 'throwing-knife',
    nameRu: 'K-2 «Метательный нож»',
    nameEn: 'K-2 Throwing Knife',
    category: 'throwable',
    warbond: 'viper',
    typeRu: 'Метательный нож',
    typeEn: 'Throwing Knife',
    imageUrl: './assets/throwables/special/K-2_Throwing_Knife_Throwable_Render.png',
  },
  {
    id: 'tm-1-lure',
    nameRu: 'TM-1 «Приманка-мина»',
    nameEn: 'TM-1 Lure Mine',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Мина-приманка',
    typeEn: 'Lure Mine',
    imageUrl: './assets/throwables/special/TM-1_Lure_Mine_Throwable_Render.png',
  },

  // --- THROWABLES/STANDART ---
  {
    id: 'incendiary-grenade',
    nameRu: 'G-10 «Зажигательная»',
    nameEn: 'G-10 Incendiary',
    category: 'throwable',
    warbond: 'default',
    typeRu: 'Зажигательная граната',
    typeEn: 'Incendiary Grenade',
    imageUrl: './assets/throwables/standart/G-10_Incendiary_Throwable_Render.png',
  },
  {
    id: 'high-explosive',
    nameRu: 'G-12 «Фугасная»',
    nameEn: 'G-12 High Explosive',
    category: 'throwable',
    warbond: 'default',
    typeRu: 'Фугасная граната',
    typeEn: 'High Explosive Grenade',
    imageUrl: './assets/throwables/standart/G-12_High_Explosive_Throwable_Render.png',
  },
  {
    id: 'frag-grenade',
    nameRu: 'G-6 «Осколочная»',
    nameEn: 'G-6 Frag',
    category: 'throwable',
    warbond: 'default',
    typeRu: 'Осколочная граната',
    typeEn: 'Frag Grenade',
    imageUrl: './assets/throwables/standart/G-6_Frag_Throwable_Render.png',
  },
  {
    id: 'g-7-pineapple',
    nameRu: 'G-7 «Ананас»',
    nameEn: 'G-7 Pineapple',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Осколочная граната',
    typeEn: 'Frag Grenade',
    imageUrl: './assets/throwables/standart/G-7_Pineapple_Throwable_Render.png',
  },
  {
    id: 'ted-63-dynamite',
    nameRu: 'TED-63 «Динамит»',
    nameEn: 'TED-63 Dynamite',
    category: 'throwable',
    warbond: 'redacted',
    typeRu: 'Взрывчатка',
    typeEn: 'Dynamite',
    imageUrl: './assets/throwables/standart/TED-63_Dynamite_Throwable_Render.png',
  },

  // --- PRIMARY WEAPONS ---
  // Assault Rifles
  {
    id: 'liberator-carbine',
    nameRu: 'AR-23A «Карабин Освободитель»',
    nameEn: 'AR-23A Liberator Carbine',
    category: 'primary',
    warbond: 'viper',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-23A_Liberator_Carbine_Primary_Render.png',
  },
  {
    id: 'liberator-concussive',
    nameRu: 'AR-23C «Сотрясающий освободитель»',
    nameEn: 'AR-23C Liberator Concussive',
    category: 'primary',
    warbond: 'steeled',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-23C_Liberator_Concussive_Primary_Render.png',
  },
  {
    id: 'liberator-penetrator',
    nameRu: 'AR-23P «Пробивной освободитель»',
    nameEn: 'AR-23P Liberator Penetrator',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-23P_Liberator_Penetrator_Primary_Render.png',
  },
  {
    id: 'liberator',
    nameRu: 'AR-23 «Освободитель»',
    nameEn: 'AR-23 Liberator',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-23_Liberator_Primary_Render.png',
  },
  {
    id: 'ar-2-coyote',
    nameRu: 'AR-2 «Койот»',
    nameEn: 'AR-2 Coyote',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-2_Coyote_Primary_Render.png',
  },
  {
    id: 'ar-32-pacifier',
    nameRu: 'AR-32 «Миротворец»',
    nameEn: 'AR-32 Pacifier',
    category: 'primary',
    warbond: 'truth',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-32_Pacifier_Primary_Render.png',
  },
  {
    id: 'suppressor-ar',
    nameRu: 'AR-59 «Глушитель»',
    nameEn: 'AR-59 Suppressor',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-59_Suppressor_Primary_Render.png',
  },
  {
    id: 'tenderizer',
    nameRu: 'AR-61 «Нежинка»',
    nameEn: 'AR-61 Tenderizer',
    category: 'primary',
    warbond: 'polar',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-61_Tenderizer_Primary_Render.png',
  },
  {
    id: 'one-two-ar',
    nameRu: 'AR/GL-21 «Раз-два»',
    nameEn: 'AR/GL-21 One-Two',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/AR-GL-21_One_Two_Primary_Render.png',
  },
  {
    id: 'adjudicator',
    nameRu: 'BR-14 «Эксперт»',
    nameEn: 'BR-14 Adjudicator',
    category: 'primary',
    warbond: 'democratic',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/BR-14_Adjudicator_Primary_Render.png',
  },
  {
    id: 'ma5c-ar',
    nameRu: 'MA5C «Штурмовая винтовка»',
    nameEn: 'MA5C Assault Rifle',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/MA5C_Assault_Rifle_Primary_Render.png',
  },
  {
    id: 'sta-52-ar',
    nameRu: 'StA-52 «Штурмовая винтовка»',
    nameEn: 'StA-52 Assault Rifle',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Штурмовая винтовка',
    typeEn: 'Assault Rifle',
    imageUrl: './assets/weapons/primary/assault_rifles/StA-52_Assault_Rifle_Primary_Render.png',
  },
  // Energy
  {
    id: 'blitzer',
    nameRu: 'ARC-12 «Налётчик»',
    nameEn: 'ARC-12 Blitzer',
    category: 'primary',
    warbond: 'cutting',
    typeRu: 'Дуговое оружие',
    typeEn: 'Arc Weapon',
    imageUrl: './assets/weapons/primary/energy/ARC-12_Blitzer_Primary_Render.png',
  },
  {
    id: 'las-13-trident',
    nameRu: 'LAS-13 «Трезубец»',
    nameEn: 'LAS-13 Trident',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Лазерный дробовик',
    typeEn: 'Laser Shotgun',
    imageUrl: './assets/weapons/primary/energy/LAS-13_Trident_Primary_Render.png',
  },
  {
    id: 'sickle',
    nameRu: 'LAS-16 «Серп»',
    nameEn: 'LAS-16 Sickle',
    category: 'primary',
    warbond: 'cutting',
    typeRu: 'Лазерное оружие',
    typeEn: 'Laser Weapon',
    imageUrl: './assets/weapons/primary/energy/LAS-16_Sickle_Primary_Render.png',
  },
  {
    id: 'las-17-double-edge',
    nameRu: 'LAS-17 «Обоюдоострый серп»',
    nameEn: 'LAS-17 Double-Edge Sickle',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Лазерное оружие',
    typeEn: 'Laser Weapon',
    imageUrl: './assets/weapons/primary/energy/LAS-17_Double-Edge_Sickle_Primary_Render.png',
  },
  {
    id: 'scythe',
    nameRu: 'LAS-5 «Коса»',
    nameEn: 'LAS-5 Scythe',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Лазерное оружие',
    typeEn: 'Laser Weapon',
    imageUrl: './assets/weapons/primary/energy/LAS-5_Scythe_Primary_Render.png',
  },
  {
    id: 'purifier',
    nameRu: 'PLAS-101 «Очиститель»',
    nameEn: 'PLAS-101 Purifier',
    category: 'primary',
    warbond: 'polar',
    typeRu: 'Плазменное оружие',
    typeEn: 'Plasma Weapon',
    imageUrl: './assets/weapons/primary/energy/PLAS-101_Purifier_Primary_Render.png',
  },
  {
    id: 'scorcher',
    nameRu: 'PLAS-1 «Поджигатель»',
    nameEn: 'PLAS-1 Scorcher',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Плазменное оружие',
    typeEn: 'Plasma Weapon',
    imageUrl: './assets/weapons/primary/energy/PLAS-1_Scorcher_Primary_Render.png',
  },
  {
    id: 'plas-39-accelerator',
    nameRu: 'PLAS-39 «Акселераторная винтовка»',
    nameEn: 'PLAS-39 Accelerator Rifle',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Энергетическая винтовка',
    typeEn: 'Energy Rifle',
    imageUrl: './assets/weapons/primary/energy/PLAS-39_Accelerator_Rifle_Primary_Render.png',
  },
  {
    id: 'punisher-plasma',
    nameRu: 'SG-8P «Плазменный каратель»',
    nameEn: 'SG-8P Punisher Plasma',
    category: 'primary',
    warbond: 'cutting',
    typeRu: 'Плазменный дробовик',
    typeEn: 'Plasma Shotgun',
    imageUrl: './assets/weapons/primary/energy/SG-8P_Punisher_Plasma_Primary_Render.png',
  },
  // Explosive
  {
    id: 'exploding-crossbow',
    nameRu: 'CB-9 «Взрывной арбалет»',
    nameEn: 'CB-9 Exploding Crossbow',
    category: 'primary',
    warbond: 'democratic',
    typeRu: 'Арбалет',
    typeEn: 'Explosive Crossbow',
    imageUrl: './assets/weapons/primary/explosive/CB-9_Exploding_Crossbow_Primary_Render.png',
  },
  {
    id: 'eruptor',
    nameRu: 'R-36 «Извергатель»',
    nameEn: 'R-36 Eruptor',
    category: 'primary',
    warbond: 'democratic',
    typeRu: 'Болтовая винтовка',
    typeEn: 'Bolt-Action Rifle',
    imageUrl: './assets/weapons/primary/explosive/R-36_Eruptor_Primary_Render.png',
  },
  // Marksman Rifles
  {
    id: 'r-2124-constitution',
    nameRu: 'R-2124 «Конституция»',
    nameEn: 'R-2124 Constitution',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-2124_Constitution_Primary_Render.png',
  },
  {
    id: 'r-2-amendment',
    nameRu: 'R-2 «Поправка»',
    nameEn: 'R-2 Amendment',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-2_Amendment_Primary_Render.png',
  },
  {
    id: 'r-4-hyena',
    nameRu: 'R-4 «Гиена»',
    nameEn: 'R-4 Hyena',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-4_Hyena_Primary_Render.png',
  },
  {
    id: 'diligence-counter-sniper',
    nameRu: 'R-63CS «Рвение антиснайпер»',
    nameEn: 'R-63CS Diligence Counter Sniper',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-63CS_Diligence_Counter_Sniper_Primary_Render.png',
  },
  {
    id: 'diligence',
    nameRu: 'R-63 «Рвение»',
    nameEn: 'R-63 Diligence',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-63_Diligence_Primary_Render.png',
  },
  {
    id: 'r-6-deadeye',
    nameRu: 'R-6 «Меткий глаз»',
    nameEn: 'R-6 Deadeye',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-6_Deadeye_Primary_Render.png',
  },
  {
    id: 'r-72-censor',
    nameRu: 'R-72 «Цензор»',
    nameEn: 'R-72 Censor',
    category: 'primary',
    warbond: 'truth',
    typeRu: 'Марксманская винтовка',
    typeEn: 'Marksman Rifle',
    imageUrl: './assets/weapons/primary/marksman_rifles/R-72_Censor_Primary_Render.png',
  },
  // Shotgun
  {
    id: 'double-freedom',
    nameRu: 'DBS-2 «Двойная свобода»',
    nameEn: 'DBS-2 Double Freedom',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Двуствольный дробовик',
    typeEn: 'Double-Barrel Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/DBS-2_Shotgun_Primary_Render.png',
  },
  {
    id: 'm90a-shotgun',
    nameRu: 'M90A «Дробовик»',
    nameEn: 'M90A Shotgun',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Дробовик',
    typeEn: 'Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/M90A_Shotgun_Primary_Render.png',
  },
  {
    id: 'sg-20-halt',
    nameRu: 'SG-20 «Стой»',
    nameEn: 'SG-20 Halt',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Дробовик',
    typeEn: 'Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-20_Halt_Primary_Render.png',
  },
  {
    id: 'breaker-incendiary',
    nameRu: 'SG-225IE «Зажигательный крушитель»',
    nameEn: 'SG-225IE Breaker Incendiary',
    category: 'primary',
    warbond: 'steeled',
    typeRu: 'Автоматический дробовик',
    typeEn: 'Automatic Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-225IE_Breaker_Incendiary_Primary_Render.png',
  },
  {
    id: 'breaker-spray-pray',
    nameRu: 'SG-225SP «Крушитель ураган»',
    nameEn: 'SG-225SP Breaker Spray & Pray',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Автоматический дробовик',
    typeEn: 'Automatic Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-225SP_Breaker_Spray&Pray_Primary_Render.png',
  },
  {
    id: 'breaker',
    nameRu: 'SG-225 «Крушитель»',
    nameEn: 'SG-225 Breaker',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Автоматический дробовик',
    typeEn: 'Automatic Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-225_Breaker_Primary_Render.png',
  },
  {
    id: 'cookout',
    nameRu: 'SG-451 «Барбекю»',
    nameEn: 'SG-451 Cookout',
    category: 'primary',
    warbond: 'flame',
    typeRu: 'Помповый дробовик',
    typeEn: 'Pump-Action Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-451_Cookout_Primary_Render.png',
  },
  {
    id: 'slugger',
    nameRu: 'SG-8S «Крушила»',
    nameEn: 'SG-8S Slugger',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Помповый дробовик',
    typeEn: 'Pump-Action Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-8S_Slugger_Primary_Render.png',
  },
  {
    id: 'punisher',
    nameRu: 'SG-8 «Каратель»',
    nameEn: 'SG-8 Punisher',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Помповый дробовик',
    typeEn: 'Pump-Action Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-8_Punisher_Primary_Render.png',
  },
  {
    id: 'sg-97-sweeper',
    nameRu: 'SG-97 «Чистильщик»',
    nameEn: 'SG-97 Sweeper',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Дробовик',
    typeEn: 'Shotgun',
    imageUrl: './assets/weapons/primary/shotgun/SG-97_Shotgun_Primary_Render.png',
  },
  // Smg
  {
    id: 'm7s-smg',
    nameRu: 'M7S «Пистолет-пулемет»',
    nameEn: 'M7S SMG',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/M7S_SMG_Primary_Render.png',
  },
  {
    id: 'knight',
    nameRu: 'MP-98 «Рыцарь»',
    nameEn: 'MP-98 Knight',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/MP-98_Knight_Primary_Render.png',
  },
  {
    id: 'smg-203-gallant',
    nameRu: 'SMG-203 «Галантный»',
    nameEn: 'SMG-203 Gallant',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/SMG-203_Gallant_Primary_Render.png',
  },
  {
    id: 'smg-32-reprimand',
    nameRu: 'SMG-32 «Выговор»',
    nameEn: 'SMG-32 Reprimand',
    category: 'primary',
    warbond: 'truth',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/SMG-32_Reprimand_Primary_Render.png',
  },
  {
    id: 'defender',
    nameRu: 'SMG-37 «Защитник»',
    nameEn: 'SMG-37 Defender',
    category: 'primary',
    warbond: 'default',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/SMG-37_Defender_Primary_Render.png',
  },
  {
    id: 'pummeler',
    nameRu: 'SMG-72 «Громила»',
    nameEn: 'SMG-72 Pummeler',
    category: 'primary',
    warbond: 'polar',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/SMG-72_Pummeler_Primary_Render.png',
  },
  {
    id: 'sta-11-smg',
    nameRu: 'StA-11 «Пистолет-пулемет»',
    nameEn: 'StA-11 SMG',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/StA-11_SMG_Primary_Render.png',
  },
  // Special
  {
    id: 'torcher',
    nameRu: 'FLAM-66 «Испепелитель»',
    nameEn: 'FLAM-66 Torcher',
    category: 'primary',
    warbond: 'flame',
    typeRu: 'Персональный огнемет',
    typeEn: 'Flamethrower',
    imageUrl: './assets/weapons/primary/special/FLAM-66_Torcher_Primary_Render.png',
  },
  {
    id: 'dominator',
    nameRu: 'JAR-5 «Угнетатель»',
    nameEn: 'JAR-5 Dominator',
    category: 'primary',
    warbond: 'steeled',
    typeRu: 'Реактивное оружие',
    typeEn: 'Jet-Assisted Weapon',
    imageUrl: './assets/weapons/primary/special/JAR-5_Dominator_Primary_Render.png',
  },
  {
    id: 'vg-70-variable',
    nameRu: 'VG-70 «Вариабельный»',
    nameEn: 'VG-70 Variable',
    category: 'primary',
    warbond: 'redacted',
    typeRu: 'Специальное оружие',
    typeEn: 'Special Weapon',
    imageUrl: './assets/weapons/primary/special/VG-70_Variable_Primary_Render.png',
  },
  {
    id: 'smg-flam-34-stoker',
    nameRu: 'SMG/FLAM-34 «Топка»',
    nameEn: 'SMG/FLAM-34 Stoker',
    category: 'primary',
    warbond: 'flame',
    typeRu: 'Пистолет-пулемет',
    typeEn: 'Submachine Gun',
    imageUrl: './assets/weapons/primary/smg/SMGFLAM-34_Stoker_Primary_Render.png',
  },

  // --- SECONDARY WEAPONS ---
  // Melee
  {
    id: 'cqc-19-stun-lance',
    nameRu: 'CQC-19 «Оглушающее копье»',
    nameEn: 'CQC-19 Stun Lance',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-19_Stun_Lance_Secondary_Render.png',
  },
  {
    id: 'melee-saber',
    nameRu: 'CQC-2 «Сабля»',
    nameEn: 'CQC-2 Saber',
    category: 'secondary',
    warbond: 'default',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-2_Saber_Secondary_Render.png',
  },
  {
    id: 'cqc-30-stun-baton',
    nameRu: 'CQC-30 «Оглушающая дубинка»',
    nameEn: 'CQC-30 Stun Baton',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-30_Stun_Baton_Secondary_Render.png',
  },
  {
    id: 'cqc-42-machete',
    nameRu: 'CQC-42 «Мачете»',
    nameEn: 'CQC-42 Machete',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-42_Machete_Secondary_Render.png',
  },
  {
    id: 'cqc-5-hatchet',
    nameRu: 'CQC-5 «Боевой топорик»',
    nameEn: 'CQC-5 Combat Hatchet',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-5_Combat_Hatchet_Secondary_Render.png',
  },
  {
    id: 'cqc-73-entrenchment',
    nameRu: 'CQC-73 «Саперная лопатка»',
    nameEn: 'CQC-73 Entrenchment Tool',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Холодное оружие ближнего боя',
    typeEn: 'Melee Weapon',
    imageUrl: './assets/weapons/secondary/melee/CQC-73_Entrenchment_Tool_Secondary_Render.png',
  },
  // Pistols
  {
    id: 'm6c-socom',
    nameRu: 'M6C/SOCOM Пистолет',
    nameEn: 'M6C/SOCOM Pistol',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/pistols/M6C-SOCOM_Pistol_Secondary_Render.png',
  },
  {
    id: 'verdict',
    nameRu: 'P-113 «Вердикт»',
    nameEn: 'P-113 Verdict',
    category: 'secondary',
    warbond: 'polar',
    typeRu: 'Пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/pistols/P-113_Verdict_Secondary_Render.png',
  },
  {
    id: 'redeemer',
    nameRu: 'P-19 «Избавитель»',
    nameEn: 'P-19 Redeemer',
    category: 'secondary',
    warbond: 'default',
    typeRu: 'Автоматический пистолет',
    typeEn: 'Automatic Pistol',
    imageUrl: './assets/weapons/secondary/pistols/P-19_Redeemer_Secondary_Render.png',
  },
  {
    id: 'peacemaker',
    nameRu: 'P-2 «Миротворец»',
    nameEn: 'P-2 Peacemaker',
    category: 'secondary',
    warbond: 'default',
    typeRu: 'Полуавтоматический пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/pistols/P-2_Peacemaker_Secondary_Render.png',
  },
  {
    id: 'senator',
    nameRu: 'P-4 «Сенатор»',
    nameEn: 'P-4 Senator',
    category: 'secondary',
    warbond: 'steeled',
    typeRu: 'Револьвер',
    typeEn: 'Revolver',
    imageUrl: './assets/weapons/secondary/pistols/P-4_Senator_Secondary_Render.png',
  },
  {
    id: 'p-69-veto',
    nameRu: 'P-69 «Вето»',
    nameEn: 'P-69 Veto',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/pistols/P-69_Veto_Secondary_Render.png',
  },
  {
    id: 'p-92-warrant',
    nameRu: 'P-92 «Ордер»',
    nameEn: 'P-92 Warrant',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/pistols/P-92_Warrant_Secondary_Render.png',
  },
  // Special
  {
    id: 'gp-20-ultimatum',
    nameRu: 'GP-20 «Ультиматум»',
    nameEn: 'GP-20 Ultimatum',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Гранатометный пистолет',
    typeEn: 'Grenade Pistol',
    imageUrl: './assets/weapons/secondary/special/GP-20_Ultimatum_Secondary_Render.png',
  },
  {
    id: 'grenade-pistol',
    nameRu: 'GP-31 «Пистолет-гранатомёт»',
    nameEn: 'GP-31 Grenade Pistol',
    category: 'secondary',
    warbond: 'democratic',
    typeRu: 'Гранатометный пистолет',
    typeEn: 'Grenade Pistol',
    imageUrl: './assets/weapons/secondary/special/GP-31_Grenade_Pistol_Secondary_Render.png',
  },
  {
    id: 'las-58-talon',
    nameRu: 'LAS-58 «Коготь»',
    nameEn: 'LAS-58 Talon',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Энергетический пистолет',
    typeEn: 'Laser Pistol',
    imageUrl: './assets/weapons/secondary/special/LAS-58_Talon_Secondary_Render.png',
  },
  {
    id: 'dagger',
    nameRu: 'LAS-7 «Кинжал»',
    nameEn: 'LAS-7 Dagger',
    category: 'secondary',
    warbond: 'cutting',
    typeRu: 'Лазерный пистолет',
    typeEn: 'Laser Pistol',
    imageUrl: './assets/weapons/secondary/special/LAS-7_Dagger_Secondary_Render.png',
  },
  {
    id: 'stim-pistol',
    nameRu: 'P-11 «Пистолет-стимулятор»',
    nameEn: 'P-11 Stim Pistol',
    category: 'secondary',
    warbond: 'chemical',
    typeRu: 'Вспомогательный пистолет',
    typeEn: 'Support Pistol',
    imageUrl: './assets/weapons/secondary/special/P-11_Stim_Pistol_Secondary_Render.png',
  },
  {
    id: 'p-33-missile-pistol',
    nameRu: 'P-33 «Ракетный пистолет»',
    nameEn: 'P-33 Missile Pistol',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Ракетный пистолет',
    typeEn: 'Missile Pistol',
    imageUrl: './assets/weapons/secondary/special/P-33_Missile_Pistol_Secondary_Render.png',
  },
  {
    id: 'p-35-reeducator',
    nameRu: 'P-35 «Реформатор»',
    nameEn: 'P-35 Re-Educator',
    category: 'secondary',
    warbond: 'redacted',
    typeRu: 'Пистолет',
    typeEn: 'Pistol',
    imageUrl: './assets/weapons/secondary/special/P-35_Re-Educator_Secondary_Render.png',
  },
  {
    id: 'crisper',
    nameRu: 'P-72 «Жаришка»',
    nameEn: 'P-72 Crisper',
    category: 'secondary',
    warbond: 'flame',
    typeRu: 'Карманный огнемет',
    typeEn: 'Pocket Flamethrower',
    imageUrl: './assets/weapons/secondary/special/P-72_Crisper_Secondary_Render.png',
  },
  {
    id: 'loyalist',
    nameRu: 'PLAS-15 «Верный»',
    nameEn: 'PLAS-15 Loyalist',
    category: 'secondary',
    warbond: 'truth',
    typeRu: 'Плазменный пистолет',
    typeEn: 'Plasma Pistol',
    imageUrl: './assets/weapons/secondary/special/PLAS-15_Loyalist_Secondary_Render.png',
  },
  {
    id: 'bushwhacker',
    nameRu: 'SG-22 «Партизан»',
    nameEn: 'SG-22 Bushwhacker',
    category: 'secondary',
    warbond: 'viper',
    typeRu: 'Обрез дробовика',
    typeEn: 'Shotgun Pistol',
    imageUrl: './assets/weapons/secondary/special/SG-22_Bushwhacker_Secondary_Render.png',
  },

  // --- CAPES ---
  {
    id: 'will-of-people',
    nameRu: 'Воля Народа',
    nameEn: 'Will of the People',
    category: 'cape',
    warbond: 'default',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/will-of-people.png',
  },
  {
    id: 'crimson-rider',
    nameRu: 'Багряный Всадник',
    nameEn: 'Crimson Rider',
    category: 'cape',
    warbond: 'steeled',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/crimson-rider.png',
  },
  {
    id: 'mantle-of-crit-over',
    nameRu: 'Мантия Настоящего Патриота',
    nameEn: 'Mantle of Critical Patriotism',
    category: 'cape',
    warbond: 'default',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/mantle-of-crit-over.png',
  },
  {
    id: 'bot-slayer',
    nameRu: 'Истребитель автоматонов',
    nameEn: 'Automaton Slayer',
    category: 'cape',
    warbond: 'default',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/bot-slayer.png',
  },
  {
    id: 'executioners-canopy',
    nameRu: 'Навес палача',
    nameEn: 'Executioner',
    category: 'cape',
    warbond: 'democratic',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/executioners-canopy.png',
  },
  {
    id: 'crest-of-shattered',
    nameRu: 'Герб разбитых надежд',
    nameEn: 'Crest of Shattered Soldiers',
    category: 'cape',
    warbond: 'polar',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/crest-of-shattered.png',
  },
  {
    id: 'mark-of-the-crimson',
    nameRu: 'Знак багряного когтя',
    nameEn: 'Mark of the Crimson Fang',
    category: 'cape',
    warbond: 'viper',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/mark-of-the-crimson.png',
  },
  {
    id: 'eclipse-of-valian',
    nameRu: 'Затмение доблести',
    nameEn: 'Eclipse of Valiance',
    category: 'cape',
    warbond: 'flame',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/eclipse-of-valian.png',
  },
  {
    id: 'standard-of-authority',
    nameRu: 'Штандарт власти',
    nameEn: 'Standard of Authority',
    category: 'cape',
    warbond: 'truth',
    typeRu: 'Плащ',
    typeEn: 'Cape',
    imageUrl: './assets/gear/capes/standard-of-authority.png',
  },

  // --- HELMETS ---
  {
    id: 'b-01-tactical-helmet',
    nameRu: 'Шлем B-01 «Тактический»',
    nameEn: 'B-01 Tactical Helmet',
    category: 'helmet',
    warbond: 'default',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/b-01-tactical-helmet.png',
  },
  {
    id: 'sc-30-trailblazer-helmet',
    nameRu: 'Шлем SC-30 «Следопыт»',
    nameEn: 'SC-30 Trailblazer Scout Helmet',
    category: 'helmet',
    warbond: 'default',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/sc-30-trailblazer-helmet.png',
  },
  {
    id: 'sa-25-steel-helmet',
    nameRu: 'Шлем SA-25 «Стальной горн»',
    nameEn: 'SA-25 Steel Trooper Helmet',
    category: 'helmet',
    warbond: 'steeled',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/sa-25-steel-helmet.png',
  },
  {
    id: 'ex-03-prototype-helmet',
    nameRu: 'Шлем EX-03 «Прототип 3»',
    nameEn: 'EX-03 Prototype 3 Helmet',
    category: 'helmet',
    warbond: 'cutting',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/ex-03-prototype-helmet.png',
  },
  {
    id: 'ce-27-ground-helmet',
    nameRu: 'Шлем CE-27 «Наземный штурмовик»',
    nameEn: 'CE-27 Ground Breaker Helmet',
    category: 'helmet',
    warbond: 'democratic',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/ce-27-ground-helmet.png',
  },
  {
    id: 'cw-9-white-helmet',
    nameRu: 'Шлем CW-9 «Белая волк»',
    nameEn: 'CW-9 White Out Helmet',
    category: 'helmet',
    warbond: 'polar',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/cw-9-white-helmet.png',
  },
  {
    id: 'ph-9-predator-helmet',
    nameRu: 'Шлем PH-9 «Хищник»',
    nameEn: 'PH-9 Predator Helmet',
    category: 'helmet',
    warbond: 'viper',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/ph-9-predator-helmet.png',
  },
  {
    id: 'i-09-heat-helmet',
    nameRu: 'Шлем I-09 «Самонаведение»',
    nameEn: 'I-09 Heatseeker Helmet',
    category: 'helmet',
    warbond: 'flame',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/i-09-heat-helmet.png',
  },
  {
    id: 'af-50-noxious-helmet',
    nameRu: 'Шлем AF-50 «Токсичный страж»',
    nameEn: 'AF-50 Noxious Ranger Helmet',
    category: 'helmet',
    warbond: 'chemical',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/af-50-noxious-helmet.png',
  },
  {
    id: 'uf-16-inspector-helmet',
    nameRu: 'Шлем UF-16 «Инспектор»',
    nameEn: 'UF-16 Inspector Helmet',
    category: 'helmet',
    warbond: 'truth',
    typeRu: 'Шлем',
    typeEn: 'Helmet',
    imageUrl: './assets/gear/helmets/uf-16-inspector-helmet.png',
  },
];
